sudo: require
language: java
jdk:
  - openjdk8
  #- openjdk9
services:
  - docker
before_install:
  - sudo apt-get update && sudo apt-get install jd


env:
  matrix:
  - COVERAGE=0.0 BUILD_TARGET=./monolithic/ui
  - COVERAGE=0.0 BUILD_TARGET=./monolithic/service/cart
  - COVERAGE=0.0 BUILD_TARGET=./monolithic/service/user
  - COVERAGE=0.0 BUILD_TARGET=./monolithic/repository/order
  - COVERAGE=0.0 BUILD_TARGET=./monolithic/repository/cart
  - COVERAGE=0.0 BUILD_TARGET=./monolithic/repository/product
  - COVERAGE=0.3 BUILD_TARGET=./monolithic/repository/user

  global:
    - DOCKER_LOGIN=tarek47
    - secure: KMYsEc02v6GZ8+h5svhtcGy0qF907wMa02FaWEEM9nuTOJpbPSJ5f8KbxaPr1LSPxWpYbiHVv9DMPmmXt+kKJhuKdz4csEmnRnJ5Eny0QruTWfn6Zaxausjby9ix7NeMTa/+PxPrZ7rRWIkAfg7w0sytCwyXgfSoAurQwRKeIybm3n1Epuz2LmJjIVxo+eEpeyOnsM5e0/qLjTMe2yO0f+z2wyssDpgtlVvu5i9goYyBka7LbT0h76CI+iORwrTM9FTkteusC1pndW17aBvFwNxSKyPqJDzuUVJP58vZUQeW9hbzrnklmF8xVAdzVPcFMC5w79c2copGRJMNQ1yS5fLsGeRApHyzjBZWDTw6dFwGghWMmJNV/vt0U0W0ALz0AHLzeD/IuVvlT6zPWAhJxZ3qeZSpTUtzxhLtic+ew2kfeRTzhqZ3XGwucxNm9AhfWliDR2oIV2M/Izucghlki7KS5Qu/2cOLxnc3fCYXwSqp3X7rLzwhklPEtUTlnNkWMZ0ch1bP2EiXg2c6WyI/jrzA53vTlIrmFpXWgvs4VbK6xrtigst6YjJ8pyTbY117tHt6k2k3Cle9BBXb57DzMPEkRqKt9Mxag6f4zUwyVx7lywMyx+OfrJaVbRLMLWTbTi7Czf0wTIkQXq/DWFhj+hXodDC1tJ7SaSsE0/DdJn8=



install:
  - ./gradlew clean jar

stages:
  -test


jobs:
  include:
    - stage: test
      after_success:

        - ./gradlew -p $BUILD_TARGET check
  #      - $COVERAGE ./gradlew -p ./monolithic/service/cart check
  #      - $COVERAGE ./gradlew -p ./monolithic/service/user check

  #      - $COVERAGE ./gradlew -p ./monolithic/repository/order check
  #      - $COVERAGE ./gradlew -p ./monolithic/repository/cart check
  #      - $COVERAGE ./gradlew -p ./monolithic/repository/product check
  #      - $COVERAGE ./gradlew -p ./monolithic/repository/user check



deploy:
  provider: script

  before_deploy:
    - "./gradlew -p ./monolithic/ui packageToContainer ;"
    - chmod +x "./script/deploy.sh"

  script: bash "./script/deploy.sh"


  on:
    all_branches: true
   # condition: "$BIULD_TARGET = ./monolithic/ui"












#install: "pip install -r requirements.txt"

#script:
  # Run ANSIBLE checks
  # - ANSIBLE0008: Disabled for use of sudo warnings - to address
  # - ANSIBLE0011: Disabled for all tasks which should be named
  # - ANSIBLE0012: Disabled (should not change if nothings needs doing) - to address
  # - ANSIBLE0013: Disabled - few uses of shell commands - to address
#  - find vagrant/provision -name "*.yml" -exec ansible-lint -x ANSIBLE008,ANSIBLE0011,ANSIBLE0012,ANSIBLE0013  {} +
