sudo: require
language: java
jdk:
  - openjdk8
  - openjdk9
before_install:
  - sudo apt-get update && sudo apt-get install jd
befor_script:
  - ./gradlew clean jar
env:
  - COVERAGE=0.0
  - COVERAGE=0.25
  - COVERAGE=0.30

stages:
  -test


jobs:
  include:
    - stage: test
      after_success:

        - $COVERAGE ./gradlew -p ./monolithic/ui check
        - $COVERAGE ./gradlew -p ./monolithic/service/cart check
        - $COVERAGE ./gradlew -p ./monolithic/service/user check

        - $COVERAGE ./gradlew -p ./monolithic/repository/order check
        - $COVERAGE ./gradlew -p ./monolithic/repository/cart check
        - $COVERAGE ./gradlew -p ./monolithic/repository/product check
        - $COVERAGE ./gradlew -p ./monolithic/repository/user check



deploy:
  provider: script
  script: echo 'WIP'

  on:
    all_branches: true





#install: "pip install -r requirements.txt"

#script:
  # Run ANSIBLE checks
  # - ANSIBLE0008: Disabled for use of sudo warnings - to address
  # - ANSIBLE0011: Disabled for all tasks which should be named
  # - ANSIBLE0012: Disabled (should not change if nothings needs doing) - to address
  # - ANSIBLE0013: Disabled - few uses of shell commands - to address
#  - find vagrant/provision -name "*.yml" -exec ansible-lint -x ANSIBLE008,ANSIBLE0011,ANSIBLE0012,ANSIBLE0013  {} +
